name: Run Unit Tests
 
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        working-directory: ./server
        run: npm install

      - name: Typecheck
        working-directory: ./server
        run: npm run typecheck

      - name: Run tests
        working-directory: ./server
        run: npm test

  test-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        working-directory: ./client
        run: npm install

      - name: Typecheck
        working-directory: ./client
        run: npm run typecheck

      - name: Run tests
        working-directory: ./client
        run: npm test
